[cmip5]
root_dir = "/mnt/data4freva/model/global"
drs_format = "cmip6"

[cmip5.defaults]
project = "cmip5"

[observations]
root_dir = "/mnt/data4freva/"
parts_dir = [
    "project", "product", "institute", "model", "experiment", "time_frequency",
    "realm", "cmor_table", "ensemble", "version", "variable", "file_name",
]
parts_file_name = ["variable", "experiment", "level", "version", "time"]
parts_time = "start_time-end_time"
drs_format = "custom"

[observations.defaults]
project = "observations"

[reanalysis]
root_dir = "/mnt/data4freva/reanalysis"
drs_format = "cmip5"

[reanalysis.defaults]
project = "reanalysis"
product = "reanalysis"

[crawl_my_data]
root_dir = "/usr/freva_output/data"
parts_dir = [
    "project", "product", "institute", "model", "experiment", "time_frequency",
    "realm", "cmor_table", "ensemble", "version", "variable", "file_name",
]
parts_file_name = [
    "variable", "cmor_table", "model", "experiment", "ensemble", "time",
]
parts_time = "start_time-end_time"
drs_format = "custom"

[crawl_my_data.defaults]
